### Consider the below code to answer further questions:

In [21]:
import numpy as np
list_ = ['1' , '2' , '3' , '4' , '5']
array_list = np.array(object = list_)

### [Q1.] Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

#### [Ans]

In [9]:
list_

['1', '2', '3', '4', '5']

In [10]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [16]:
print("THE DATA TYPE OF list_ IS :",type(list_))
print("THE DATA TYPE OF array_list IS :",type(array_list))

THE DATA TYPE OF list_ IS :  <class 'list'>
THE DATA TYPE OF array_list IS :  <class 'numpy.ndarray'>


### [Q2.] Write a code to print the data type of each and every element of both the variables list_ and array_list.

#### [Ans]

In [17]:
for i in list_:
    print(f"THE DATA TYPE OF {i} IS :",type(i))
    
print("======="*8)

for j in array_list:
    print(f"THE DATA TYPE OF {j} IS :",type(j))

THE DATA TYPE OF 1 IS : <class 'str'>
THE DATA TYPE OF 2 IS : <class 'str'>
THE DATA TYPE OF 3 IS : <class 'str'>
THE DATA TYPE OF 4 IS : <class 'str'>
THE DATA TYPE OF 5 IS : <class 'str'>
THE DATA TYPE OF 1 IS : <class 'numpy.str_'>
THE DATA TYPE OF 2 IS : <class 'numpy.str_'>
THE DATA TYPE OF 3 IS : <class 'numpy.str_'>
THE DATA TYPE OF 4 IS : <class 'numpy.str_'>
THE DATA TYPE OF 5 IS : <class 'numpy.str_'>


### [Q3.] Considering the following changes in the variable, array_list:

In [18]:
array_list = np.array(object=list_ , dtype=int)

#### Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.

##### [Ans]

In [19]:
for m in list_:
    print(f"THE DATA TYPE OF {m} IS :",type(m))
    
print("======="*8)

for n in array_list:
    print(f"THE DATA TYPE OF {n} IS :",type(n))

THE DATA TYPE OF 1 IS : <class 'str'>
THE DATA TYPE OF 2 IS : <class 'str'>
THE DATA TYPE OF 3 IS : <class 'str'>
THE DATA TYPE OF 4 IS : <class 'str'>
THE DATA TYPE OF 5 IS : <class 'str'>
THE DATA TYPE OF 1 IS : <class 'numpy.int64'>
THE DATA TYPE OF 2 IS : <class 'numpy.int64'>
THE DATA TYPE OF 3 IS : <class 'numpy.int64'>
THE DATA TYPE OF 4 IS : <class 'numpy.int64'>
THE DATA TYPE OF 5 IS : <class 'numpy.int64'>


### Consider the below code to answer further questions:

In [22]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

### [Q4.] Write a code to find the following characteristics of variable, num_array:
#### (i) shape
#### (ii) size

##### [Ans]

In [24]:
print("THE SHAPE OF num_array IS :",num_array.shape)
print("THE SIZE OF num_array IS :",num_array.size)

THE SHAPE OF num_array IS : (2, 3)
THE SIZE OF num_array IS : 6


### [Q5.] Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

#### [Hint: The size of the array will be 9 and the shape will be (3,3).]

##### [Ans]

In [32]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### [Q6.] Create an identity matrix of shape (5,5) using numpy functions?

#### [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

##### [Ans]

In [34]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])